### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by mkaliyannan** [PaulSec/API-dnsdumpster.com#14]
I tried to run DNS dumpster for   googlevideo.com. Then I got an error below. I tried microsoft domain, seems working. 

python test.py
[verbose] Retrieved token: f85dwWRTXhLGvpKj58eD7LRT70MMQeuS
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    res = DNSDumpsterAPI({'verbose': False}).search('googlevideo.com')
  File "/usr/lib/python2.7/site-packages/dnsdumpster/DNSDumpsterAPI.py", line 95, in search
    res['dns_records']['host'] = self.retrieve_results(tables[3])
  File "/usr/lib/python2.7/site-packages/dnsdumpster/DNSDumpsterAPI.py", line 33, in retrieve_results
    ip = re.findall(pattern_ip, tds[1].text)[0]
IndexError: list index out of range

**Comment by PaulSec** [comment]
I am going to investigate it right now

**Comment by mkaliyannan** [comment]
Thank you so much. Really appreciated

**Comment by PaulSec** [comment]
I just pushed a quick fix, catching an exception in the Host records table. That was because the first entry in the Host record table was not containing any IP etc.

Bare in mind that the DNSDumpster service added few more fields in this table and I am currently updating my scraping in order to grab all of them :+1:

**Comment by mkaliyannan** [comment]
Thank you so much @PaulSec . Much appriciated.

**Comment by mkaliyannan** [comment]
@PaulSec . I  pull the changes and tested again. seems still not working. same error.

**Comment by PaulSec** [comment]
Mmmh.. did you try: 

```bash
pip3 uninstall dnsdumpster
```

Then: 

```bash
pip3 install . 
```

Let me know if that works.

**Comment by th3hack3rwiz** [comment]
I pulled the fix and also updated dnsdumpster. Didn't work for me.

**Comment by nourmuj** [comment]
Fix didn't work for me!!??
